packages:
  - apps/api
  - apps/web
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@sentry/cli'
  - prisma
  - sharp
  - unrs-resolver
  - '@openapitools/openapi-generator-cli'
  - '@nestjs/cli'
