/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/horarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Horarios vigentes del negocio */
        get: operations["listarHorarios"];
        put?: never;
        /** Agrega un horario de servicio */
        post: operations["crearHorario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado de la API y la base */
        get: operations["consultarSalud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CrearHorarioRequest: {
            /**
             * @description Código del día (catálogo de días)
             * @example MONDAY
             */
            dia: string;
            /** @example 15:00 */
            horaFin: string;
            /** @example 11:30 */
            horaInicio: string;
            /**
             * Format: uuid
             * @description Sede donde aplica el horario
             */
            sedeId: string;
            /**
             * Format: uuid
             * @description Servicio (desayuno, almuerzo...)
             */
            servicioId: string;
        };
        HorarioResponse: {
            /** @example MONDAY */
            dia: string;
            /** @example 15:00 */
            horaFin: string;
            /** @example 11:30 */
            horaInicio: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sedeId: string;
            /** Format: uuid */
            servicioId: string;
            /** @example Almuerzo */
            servicioNombre?: string;
        };
        RespuestaErrorDto: {
            /** @example HORARIO_SE_CRUZA */
            codigo: string;
            /** @example Ese horario se cruza con otro del mismo día en esta sede. */
            message: string;
            /** @example 422 */
            statusCode: number;
        };
        SaludResponse: {
            /** @enum {string} */
            baseDatos: "ok" | "sin-conexion";
            /** @enum {string} */
            estado: "ok" | "degradado";
            /** @example 0.1.0+abc1234 */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listarHorarios: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
                /** @description Solo desarrollo y staging, hasta EP-02: id del usuario */
                "x-veci-usuario"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioResponse"][];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El usuario no trabaja en ese negocio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    crearHorario: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
                /** @description Solo desarrollo y staging, hasta EP-02: id del usuario */
                "x-veci-usuario"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearHorarioRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El usuario no trabaja en ese negocio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El servicio o la sede no son del negocio */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Se cruza con otro horario */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Horas o día inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    consultarSalud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludResponse"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludResponse"];
                };
            };
        };
    };
}
