/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/comercio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datos, plan y camino para abrir */
        get: operations["consultarComercio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambia los datos del negocio */
        patch: operations["editarComercio"];
        trace?: never;
    };
    "/comercio/abrir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre el negocio para vender */
        post: operations["abrirComercio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comercios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra un negocio propio (HU-03-01) */
        post: operations["registrarComercio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comercios/municipios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Municipios donde opera VECI */
        get: operations["listarMunicipios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comercios/tipos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tipos de negocio y servicios */
        get: operations["listarTiposDeNegocio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cuenta/comercio-activo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Elige el negocio con el que trabajo */
        post: operations["elegirComercio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cuenta/correo-y-contrasena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Correo y contraseña para entrar al panel (HU-02-02) */
        put: operations["definirCorreoYContrasena"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cuenta/espacios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comercios donde trabajo o soy cliente */
        get: operations["listarMisEspacios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cuenta/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambia mi PIN */
        put: operations["cambiarMiPin"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispositivos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Celulares de la caja y sus sesiones */
        get: operations["listarDispositivos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispositivos/{dispositivoId}/cerrar-sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cierre remoto (HU-02-06) */
        post: operations["cerrarSesionDispositivo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Propietarios y cajeros del negocio */
        get: operations["listarEquipo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipo/{membresiaId}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Suspende, reactiva o retira */
        patch: operations["cambiarEstadoCajero"];
        trace?: never;
    };
    "/equipo/{membresiaId}/restablecer-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** PIN temporal para un cajero (HU-02-05) */
        post: operations["restablecerPinCajero"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipo/cajeros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invita un cajero por su celular (HU-02-04) */
        post: operations["invitarCajero"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/horarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Horarios vigentes del negocio */
        get: operations["listarHorarios"];
        put?: never;
        /** Agrega un horario en uno o varios días */
        post: operations["crearHorario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/horarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambia las horas desde hoy (devuelve el horario con su id nuevo) */
        patch: operations["editarHorario"];
        trace?: never;
    };
    "/horarios/{id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Pone en pausa o reanuda */
        patch: operations["cambiarEstadoHorario"];
        trace?: never;
    };
    "/plataforma/comercios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Administración VECI registra un negocio e invita a su dueño (HU-03-01) */
        post: operations["registrarComercioParaPropietario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado de la API y la base */
        get: operations["consultarSalud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sedes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sedes, cajeros por sede y cupo del plan */
        get: operations["listarSedes"];
        put?: never;
        /** Abre otra sede (plan Pro, HU-03-03) */
        post: operations["crearSede"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sedes/{sedeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambia, desactiva o reabre una sede */
        patch: operations["editarSede"];
        trace?: never;
    };
    "/sedes/cajeros/{membresiaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Sedes donde trabaja un cajero */
        put: operations["asignarSedesACajero"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servicios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Servicios del negocio */
        get: operations["listarServicios"];
        put?: never;
        /** Agrega un servicio (cena, onces...) */
        post: operations["crearServicio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sesion/con-contrasena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Entra al panel con correo (HU-02-02) */
        post: operations["entrarConContrasena"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sesion/con-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Entra con celular y PIN (HU-02-01) */
        post: operations["entrarConPin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sesion/pin-nuevo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea el PIN propio tras uno temporal */
        post: operations["crearPinNuevo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sesion/renovar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cambia el token de renovación por otro */
        post: operations["renovarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sesion/salir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cierra la sesión en este dispositivo */
        post: operations["salir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/soporte/clientes/restablecer-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restablece el PIN de un cliente tras verificar su documento (HU-02-05) */
        post: operations["restablecerPinCliente"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AsignarSedesRequest: {
            /** @description Vacío = trabaja en todas las sedes */
            sedeIds: string[];
        };
        AvanceResponse: {
            /** @example 1 */
            cajeros: number;
            /** @example 2 */
            serviciosConHorario: number;
            /** @example 0 */
            tiqueteras: number;
        };
        CajeroEnSedesResponse: {
            /** Format: uuid */
            membresiaId: string;
            /** @example Jhon Mutumbajoy */
            nombre: string;
            /** @description Vacío = trabaja en todas */
            sedeIds: string[];
        };
        CambiarEstadoCajeroRequest: {
            /** @enum {string} */
            accion: "SUSPENDER" | "REACTIVAR" | "RETIRAR";
        };
        CambiarPinRequest: {
            pinActual: string;
            pinNuevo: string;
        };
        CierreRemotoResponse: {
            /** @example 1 */
            sesionesCerradas: number;
        };
        ComercioActivoRequest: {
            /** Format: uuid */
            comercioId: string;
        };
        ComercioActivoResponse: {
            comercio: components["schemas"]["EspacioResponse"];
            /**
             * @example [
             *       "consumptions.register"
             *     ]
             */
            permisos: string[];
        };
        ComercioRegistradoResponse: {
            /** Format: uuid */
            comercioId: string;
            /**
             * @description Solo al registrar a nombre de otra persona sin PIN propio. Se muestra una vez.
             * @example 482915
             */
            pinTemporal?: string | null;
            /** @example restaurante-la-vecina */
            slug: string;
        };
        ContactoResponse: {
            /** @example +573100000101 */
            celular?: string | null;
            correo?: string | null;
        };
        CorreoResponse: {
            /** @example marta@lavecina.co */
            correo: string;
        };
        CorreoYContrasenaRequest: {
            /** @example almuerzo2026 */
            contrasena: string;
            /** @example marta@lavecina.co */
            correo: string;
            /** @description PIN actual, para confirmar que eres tú */
            pinActual: string;
        };
        CrearHorarioRequest: {
            /**
             * @description Códigos de los días (catálogo de días). Varios copian el horario.
             * @example [
             *       "MONDAY",
             *       "TUESDAY"
             *     ]
             */
            dias: string[];
            /** @example 15:00 */
            horaFin: string;
            /** @example 11:30 */
            horaInicio: string;
            /**
             * Format: uuid
             * @description Sede donde aplica el horario
             */
            sedeId: string;
            /**
             * Format: uuid
             * @description Servicio (desayuno, almuerzo...)
             */
            servicioId: string;
        };
        CrearSedeRequest: {
            /** @example Calle 8 # 5-20 */
            direccion?: string | null;
            /** @example 86001 */
            municipioId?: number | null;
            /** @example Sede del parque */
            nombre: string;
        };
        CrearServicioRequest: {
            /** @example Cena */
            nombre: string;
        };
        CupoDeSedesResponse: {
            /** @description null = sin límite */
            limite?: number | null;
            /** @example 1 */
            ocupadas: number;
            /** @description El plan permite varias sedes (plan Pro) */
            variasSedes: boolean;
        };
        DispositivoRequest: {
            /**
             * Format: uuid
             * @description Id que el dispositivo generó para sí
             */
            id: string;
            /** @example Moto E13 */
            modelo?: string;
            /** @enum {string} */
            plataforma: "ANDROID" | "IOS" | "WEB";
            /** @example 0.2.0 */
            versionApp?: string;
            /** @example Android 13 */
            versionSo?: string;
        };
        DispositivoResponse: {
            /** Format: uuid */
            dispositivoId: string;
            /** @example Moto E13 */
            nombre?: string | null;
            /** @example ANDROID */
            plataforma: string;
            /** Format: date-time */
            registradoEn: string;
            sesiones: components["schemas"]["SesionEnDispositivoResponse"][];
            /** Format: date-time */
            ultimaVez: string;
        };
        DocumentoResponse: {
            /**
             * @description El NIT incluye el dígito de verificación
             * @example 9001234567
             */
            numero: string;
            /** @enum {string} */
            tipo: "NIT" | "CC";
        };
        EditarComercioRequest: {
            /** @example 310 000 0101 */
            celular?: string;
            /** @description null lo quita */
            correo?: string | null;
            /** @description null lo quita */
            logoUrl?: string | null;
            /** @example Restaurante La Vecina */
            nombre?: string;
            /** @example RESTAURANT */
            tipoNegocio?: string;
        };
        EditarHorarioRequest: {
            /** @example 15:00 */
            horaFin: string;
            /** @example 11:30 */
            horaInicio: string;
        };
        EditarSedeRequest: {
            /** @description false desactiva la sede; true la reabre */
            activa?: boolean;
            direccion?: string | null;
            municipioId?: number | null;
            /** @example Sede del parque */
            nombre?: string;
        };
        EspacioResponse: {
            /** Format: uuid */
            comercioId: string;
            /** @description Lo invitaron como cajero y aún no ha entrado a este negocio */
            invitacionPendiente: boolean;
            /** @example Restaurante La Vecina */
            nombre: string;
            /**
             * @description OWNER, CASHIER o CUSTOMER
             * @example [
             *       "CASHIER"
             *     ]
             */
            roles: string[];
            /**
             * @description Código del tipo de negocio
             * @example RESTAURANT
             */
            tipoNegocio: string;
        };
        EstadoHorarioRequest: {
            /** @description false lo pone en pausa; true lo reanuda */
            activo: boolean;
        };
        HorarioResponse: {
            /** @description false = en pausa: no cuenta para la caja */
            activo: boolean;
            /** @example MONDAY */
            dia: string;
            /** @example 15:00 */
            horaFin: string;
            /** @example 11:30 */
            horaInicio: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sedeId: string;
            /** Format: uuid */
            servicioId: string;
            /** @example Almuerzo */
            servicioNombre?: string;
        };
        IngresoConContrasenaRequest: {
            /** @example almuerzo2026 */
            contrasena: string;
            /** @example marta@lavecina.co */
            correo: string;
            dispositivo: components["schemas"]["DispositivoRequest"];
        };
        IngresoConPinRequest: {
            /**
             * @description Celular como lo escribe la persona
             * @example 310 000 0102
             */
            celular: string;
            dispositivo: components["schemas"]["DispositivoRequest"];
            /** @example 482915 */
            pin: string;
        };
        IngresoResponse: {
            /** @example Jhon */
            nombre: string;
            /** @description Entró con un PIN temporal: debe crear el suyo antes de seguir */
            requiereCambioDePin: boolean;
            sesion?: components["schemas"]["SesionResponse"];
            /** @description Solo si requiereCambioDePin. Dura 10 minutos. */
            tokenCambio?: string;
        };
        InvitacionResponse: {
            /** Format: uuid */
            membresiaId: string;
            /**
             * @description Se muestra una sola vez. null si la persona ya tenía PIN propio.
             * @example 482915
             */
            pinTemporal?: string | null;
        };
        InvitarCajeroRequest: {
            /** @example Jacanamejoy */
            apellidos?: string;
            /** @example 312 456 7890 */
            celular: string;
            /** @example Ana Lucía */
            nombres: string;
            /** @example 1124500777 */
            numeroDocumento: string;
            /**
             * @description Código del tipo de documento (catálogo)
             * @example CC
             */
            tipoDocumento: string;
        };
        MapaDeSedesResponse: {
            cajeros: components["schemas"]["CajeroEnSedesResponse"][];
            cupo: components["schemas"]["CupoDeSedesResponse"];
            sedes: components["schemas"]["SedeResponse"][];
        };
        MiembroResponse: {
            /** @example +573100000102 */
            celular?: string | null;
            /** @enum {string} */
            estado: "INVITED" | "ACTIVE" | "SUSPENDED" | "REMOVED";
            /** Format: uuid */
            membresiaId: string;
            /** @example Jhon Mutumbajoy */
            nombre: string;
            /**
             * @example [
             *       "CASHIER"
             *     ]
             */
            roles: string[];
            /** Format: uuid */
            usuarioId: string;
        };
        MunicipioResponse: {
            /** @example 86001 */
            id: number;
            /** @example Mocoa */
            nombre: string;
        };
        PasoResponse: {
            /** @enum {string} */
            codigo: "DATOS" | "HORARIOS" | "EQUIPO" | "TIQUETERAS";
            listo: boolean;
            /** @description Si falta, impide abrir el negocio */
            obligatorio: boolean;
        };
        PerfilComercioResponse: {
            /** @description Ya vende y registra consumos */
            abierto: boolean;
            avance: components["schemas"]["AvanceResponse"];
            camino: components["schemas"]["PasoResponse"][];
            /** Format: uuid */
            comercioId: string;
            contacto: components["schemas"]["ContactoResponse"];
            documento: components["schemas"]["DocumentoResponse"];
            /** @example ONBOARDING */
            estado: string;
            logoUrl?: string | null;
            /** @example Restaurante La Vecina */
            nombre: string;
            plan?: components["schemas"]["PlanResponse"] | null;
            puedeAbrir: boolean;
            /** @example la-vecina */
            slug: string;
            /** @example RESTAURANT */
            tipoNegocio: string;
        };
        PinClienteResponse: {
            /**
             * @description Nombre enmascarado para confirmar
             * @example Luz Marina C.
             */
            nombre: string;
            /**
             * @description Se dicta una sola vez a la persona
             * @example 730284
             */
            pinTemporal: string;
        };
        PinNuevoRequest: {
            dispositivo: components["schemas"]["DispositivoRequest"];
            /** @example 730284 */
            pinNuevo: string;
            /** @description Token que entregó el ingreso con PIN temporal */
            tokenCambio: string;
        };
        PinTemporalResponse: {
            /**
             * @description Se muestra una sola vez
             * @example 482915
             */
            pinTemporal: string;
        };
        PlanResponse: {
            /** @example TRIAL */
            codigo: string;
            /** @example TRIAL */
            estado: string;
            /** @example Prueba */
            nombre: string;
            /**
             * @description Fecha local del negocio
             * @example 2026-11-05
             */
            venceEl: string;
        };
        PropietarioInvitadoRequest: {
            /** @example Chindoy */
            apellidos?: string;
            /** @example 312 456 7890 */
            celular: string;
            /** @example Rosa Elena */
            nombres: string;
            /** @example 1124500777 */
            numeroDocumento: string;
            /** @example CC */
            tipoDocumento: string;
        };
        RegistrarComercioRequest: {
            /** @example 310 000 0101 */
            celular: string;
            /** @example hola@lavecina.co */
            correo?: string | null;
            /** @example Barrio San Agustín */
            direccion?: string | null;
            /** @example https://lavecina.co/logo.png */
            logoUrl?: string | null;
            /**
             * @description Municipio (DIVIPOLA) de la sede principal
             * @example 86001
             */
            municipioId?: number | null;
            /** @example Restaurante La Vecina */
            nombre: string;
            /**
             * @description NIT con o sin dígito de verificación
             * @example 900123456
             */
            numeroDocumento: string;
            /** @enum {string} */
            tipoDocumento: "NIT" | "CC";
            /**
             * @description Código del tipo de negocio (catálogo)
             * @example RESTAURANT
             */
            tipoNegocio: string;
        };
        RegistrarParaPropietarioRequest: {
            /** @example 310 000 0101 */
            celular: string;
            /** @example hola@lavecina.co */
            correo?: string | null;
            /** @example Barrio San Agustín */
            direccion?: string | null;
            /** @example https://lavecina.co/logo.png */
            logoUrl?: string | null;
            /**
             * @description Municipio (DIVIPOLA) de la sede principal
             * @example 86001
             */
            municipioId?: number | null;
            /** @example Restaurante La Vecina */
            nombre: string;
            /**
             * @description NIT con o sin dígito de verificación
             * @example 900123456
             */
            numeroDocumento: string;
            propietario: components["schemas"]["PropietarioInvitadoRequest"];
            /** @enum {string} */
            tipoDocumento: "NIT" | "CC";
            /**
             * @description Código del tipo de negocio (catálogo)
             * @example RESTAURANT
             */
            tipoNegocio: string;
        };
        RenovarSesionRequest: {
            tokenRenovacion: string;
        };
        RespuestaErrorDto: {
            /** @example HORARIO_SE_CRUZA */
            codigo: string;
            /** @example Ese horario se cruza con otro del mismo día en esta sede. */
            message: string;
            /** @example 422 */
            statusCode: number;
        };
        RestablecerPinClienteRequest: {
            /** @example 310 000 0103 */
            celular: string;
            /**
             * @description El que dice la persona por teléfono
             * @example 1124500003
             */
            numeroDocumento: string;
            /** @example CC */
            tipoDocumento: string;
        };
        SaludResponse: {
            /** @enum {string} */
            baseDatos: "ok" | "sin-conexion";
            /** @enum {string} */
            estado: "ok" | "degradado";
            /** @example 0.1.0+abc1234 */
            version: string;
        };
        SedeResponse: {
            activa: boolean;
            direccion?: string | null;
            /** @example ACTIVE */
            estado: string;
            /** @example Mocoa */
            municipio?: string | null;
            municipioId?: number | null;
            /** @example Principal */
            nombre: string;
            principal: boolean;
            /** Format: uuid */
            sedeId: string;
        };
        ServicioResponse: {
            /** Format: uuid */
            id: string;
            /** @example Almuerzo */
            nombre: string;
        };
        ServicioSugeridoResponse: {
            /** @example 15:00 */
            horaFin: string;
            /** @example 11:30 */
            horaInicio: string;
            /** @example Almuerzo */
            nombre: string;
        };
        SesionEnDispositivoResponse: {
            /** Format: date-time */
            abiertaDesde: string;
            /** @example Jhon */
            nombre: string;
            /** Format: uuid */
            sesionId: string;
            /** Format: date-time */
            ultimoUso: string;
            /** Format: uuid */
            usuarioId: string;
        };
        SesionResponse: {
            espacios: components["schemas"]["EspacioResponse"][];
            /** @example 900 */
            segundosAcceso: number;
            /** @description Va en Authorization: Bearer. Dura 15 minutos. */
            tokenAcceso: string;
            /** @description Se cambia por uno nuevo en cada renovación; guárdelo seguro. */
            tokenRenovacion: string;
            usuario: components["schemas"]["UsuarioResponse"];
        };
        TipoDeNegocioResponse: {
            /** @example RESTAURANT */
            codigo: string;
            /** @example Restaurante */
            nombre: string;
            servicios: components["schemas"]["ServicioSugeridoResponse"][];
        };
        UsuarioResponse: {
            /** Format: uuid */
            id: string;
            /** @example Jhon */
            nombre: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    consultarComercio: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfilComercioResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Requiere el permiso tenancy.view_tenant
             *
             *     El usuario no trabaja en ese negocio o su rol no alcanza
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    editarComercio: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditarComercioRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfilComercioResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Requiere el permiso tenancy.manage_tenant
             *
             *     El usuario no trabaja en ese negocio o su rol no alcanza
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Datos inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    abrirComercio: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfilComercioResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Requiere el permiso tenancy.manage_tenant
             *
             *     El usuario no trabaja en ese negocio o su rol no alcanza
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ya estaba abierto */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta un horario */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    registrarComercio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarComercioRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComercioRegistradoResponse"];
                };
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Datos inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    listarMunicipios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipioResponse"][];
                };
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listarTiposDeNegocio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoDeNegocioResponse"][];
                };
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    elegirComercio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComercioActivoRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComercioActivoResponse"];
                };
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No es uno de mis negocios */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    definirCorreoYContrasena: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorreoYContrasenaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorreoResponse"];
                };
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El correo es de otra cuenta */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Contraseña débil */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    listarMisEspacios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EspacioResponse"][];
                };
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cambiarMiPin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambiarPinRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PIN débil */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    listarDispositivos: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispositivoResponse"][];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Requiere el permiso tenancy.revoke_devices
             *
             *     El usuario no trabaja en ese negocio o su rol no alcanza
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cerrarSesionDispositivo: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path: {
                dispositivoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CierreRemotoResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Requiere el permiso tenancy.revoke_devices
             *
             *     El usuario no trabaja en ese negocio o su rol no alcanza
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    listarEquipo: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroResponse"][];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Requiere el permiso tenancy.manage_staff
             *
             *     El usuario no trabaja en ese negocio o su rol no alcanza
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cambiarEstadoCajero: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path: {
                membresiaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambiarEstadoCajeroRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Requiere el permiso tenancy.manage_staff
             *
             *     El usuario no trabaja en ese negocio o su rol no alcanza
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Cambio no permitido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    restablecerPinCajero: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path: {
                membresiaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinTemporalResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso tenancy.reset_staff_pin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    invitarCajero: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitarCajeroRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitacionResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Requiere el permiso tenancy.manage_staff
             *
             *     El usuario no trabaja en ese negocio o su rol no alcanza
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin cupo, ya está o otro celular */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Datos inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    listarHorarios: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
                /** @description ETag de la copia local */
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioResponse"][];
                };
            };
            /** @description La copia local está al día */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso tenancy.view_tenant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    crearHorario: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearHorarioRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioResponse"][];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso tenancy.manage_schedules */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El servicio o la sede no son del negocio */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Se cruza con otro horario */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Horas o día inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    editarHorario: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditarHorarioRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso tenancy.manage_schedules */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Se cruza con otro horario */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    cambiarEstadoHorario: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstadoHorarioRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso tenancy.manage_schedules */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Al reanudar se cruza con otro */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    registrarComercioParaPropietario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarParaPropietarioRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComercioRegistradoResponse"];
                };
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso platform.manage_tenants */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El celular es de otra persona */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Datos inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    consultarSalud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludResponse"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludResponse"];
                };
            };
        };
    };
    listarSedes: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapaDeSedesResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso tenancy.view_tenant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    crearSede: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearSedeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SedeResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso tenancy.manage_branches */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El plan no lo permite */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    editarSede: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path: {
                sedeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditarSedeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SedeResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso tenancy.manage_branches */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description La principal no se cierra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    asignarSedesACajero: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path: {
                membresiaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AsignarSedesRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso tenancy.manage_branches, tenancy.manage_staff */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    listarServicios: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicioResponse"][];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso tenancy.view_tenant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    crearServicio: {
        parameters: {
            query?: never;
            header: {
                /** @description Id del negocio activo */
                "x-veci-comercio": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearServicioRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicioResponse"];
                };
            };
            /** @description Falta el negocio activo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso tenancy.manage_schedules */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ya existe con ese nombre */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    entrarConContrasena: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngresoConContrasenaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngresoResponse"];
                };
            };
            /** @description No coinciden o bloqueada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    entrarConPin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngresoConPinRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngresoResponse"];
                };
            };
            /** @description No coinciden o bloqueada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Cuenta pausada por VECI */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    crearPinNuevo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinNuevoRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionResponse"];
                };
            };
            /** @description El paso se venció */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description PIN débil */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    renovarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenovarSesionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionResponse"];
                };
            };
            /** @description Sesión cerrada o vencida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    salir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restablecerPinCliente: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestablecerPinClienteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinClienteResponse"];
                };
            };
            /** @description Sin sesión o sesión cerrada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere el permiso platform.reset_customer_pin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Celular sin cuenta */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Documento distinto */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
}
